development:
  adapter: postgresql
  encoding: unicode
  database: notesdb
  pool: 2
  username: alaa
  password: 123456
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: notesdb
  pool: 2
  username: alaa
  password: 123456
  host: localhost
